/*
 * This source file was generated by the Gradle 'init' task
 */
package org.main;

public class App {
    public static void main(String[] args) {
        // Main Runner
        String testFunc = RgbToHex.rgb(-20, 275, 125);
        System.out.println(testFunc);
    }
}
