/*
 * This source file was generated by the Gradle 'init' task
 */
package org.main;

public class App {
    public static void main(String[] args) {
        // Main Runner
        String test = "abcddea";
        String[] testFunc = StringSplit.solution(test);

        for (int i = 0; i < testFunc.length; ++i) {
            System.out.println(testFunc[i]);
        }
    }
}
