/*
 * This source file was generated by the Gradle 'init' task
 */
package org.main;

public class App {
    public static void main(String[] args) {
        // Main Runner
        Conversion conversion = new Conversion();
        String testFunc = conversion.solution(20);
        System.out.println(testFunc);
    }
}
